export const products = [
    {
        id: 1,
        name: "Running Shoes",
        price: 129.99,
        description: "Lightweight shoes with breathable mesh and cushioned soles for jogging and gym.",
        image: "https://source.unsplash.com/400x400/?running-shoes,sneakers",
        category: "Footwear",
    },
    {
        id: 2,
        name: "Classic Watch",
        price: 249.99,
        description: "Stainless steel, water-resistant wristwatch with chronograph features.",
        image: "https://source.unsplash.com/400x400/?watch,wristwatch",
        category: "Accessories",
    },
    {
        id: 3,
        name: "Wireless Earbuds",
        price: 59.99,
        description: "Noise-cancelling earbuds with clear sound and long battery life.",
        image: "https://source.unsplash.com/400x400/?wireless-earbuds,earphones",
        category: "Electronics",
    },
    {
        id: 4,
        name: "LED Desk Lamp",
        price: 39.99,
        description: "Adjustable brightness lamp with USB charging port.",
        image: "https://source.unsplash.com/400x400/?desk-lamp,lamp",
        category: "Home",
    },
    {
        id: 5,
        name: "Office Chair",
        price: 199.99,
        description: "Ergonomic chair with lumbar support and adjustable armrests.",
        image: "https://source.unsplash.com/400x400/?office-chair,furniture",
        category: "Furniture",
    },
    {
        id: 6,
        name: "4K Monitor",
        price: 349.99,
        description: "27-inch 4K display with vibrant colors and ultra-thin bezel.",
        image: "https://source.unsplash.com/400x400/?computer-monitor,technology",
        category: "Electronics",
    },
    {
        id: 7,
        name: "Casual Sneakers",
        price: 89.99,
        description: "Comfortable sneakers for everyday wear.",
        image: "https://source.unsplash.com/400x400/?casual-sneakers,footwear",
        category: "Footwear",
    },
    {
        id: 8,
        name: "Sports Watch",
        price: 179.99,
        description: "Durable watch with stopwatch and water resistance.",
        image: "https://source.unsplash.com/400x400/?sports-watch,watch",
        category: "Accessories",
    },
    {
        id: 9,
        name: "Gaming Headset",
        price: 79.99,
        description: "Surround sound headset with noise-cancelling mic.",
        image: "https://source.unsplash.com/400x400/?gaming-headset,headphones",
        category: "Electronics",
    },
    {
        id: 10,
        name: "Smartphone Stand",
        price: 15.99,
        description: "Adjustable phone holder for desk or nightstand.",
        image: "https://source.unsplash.com/400x400/?smartphone-stand,phone",
        category: "Home",
    },
    {
        id: 11,
        name: "Wooden Bookshelf",
        price: 129.99,
        description: "5-tier bookshelf made from solid wood.",
        image: "https://source.unsplash.com/400x400/?wooden-bookshelf,furniture",
        category: "Furniture",
    },
    {
        id: 12,
        name: "Bluetooth Speaker",
        price: 49.99,
        description: "Portable speaker with rich bass and long battery life.",
        image: "https://source.unsplash.com/400x400/?bluetooth-speaker,speaker",
        category: "Electronics",
    },
    {
        id: 13,
        name: "Flip Flops",
        price: 19.99,
        description: "Lightweight and comfortable beach flip flops.",
        image: "https://source.unsplash.com/400x400/?flip-flops,footwear",
        category: "Footwear",
    },
    {
        id: 14,
        name: "Leather Wallet",
        price: 39.99,
        description: "Slim wallet made of genuine leather.",
        image: "https://source.unsplash.com/400x400/?leather-wallet,wallet",
        category: "Accessories",
    },
    {
        id: 15,
        name: "Desk Organizer",
        price: 25.99,
        description: "Multi-compartment organizer for office supplies.",
        image: "https://source.unsplash.com/400x400/?desk-organizer,office",
        category: "Home",
    },
    {
        id: 16,
        name: "Dining Chair",
        price: 89.99,
        description: "Comfortable dining chair with cushioned seat.",
        image: "https://source.unsplash.com/400x400/?dining-chair,furniture",
        category: "Furniture",
    },
    {
        id: 17,
        name: "Smartwatch",
        price: 199.99,
        description: "Fitness smartwatch with heart rate monitor.",
        image: "https://source.unsplash.com/400x400/?smartwatch,fitness",
        category: "Electronics",
    },
    {
        id: 18,
        name: "Trail Running Shoes",
        price: 139.99,
        description: "Durable shoes designed for trail running.",
        image: "https://source.unsplash.com/400x400/?trail-running-shoes,footwear",
        category: "Footwear",
    },
    {
        id: 19,
        name: "Sunglasses",
        price: 49.99,
        description: "UV-protective stylish sunglasses.",
        image: "https://source.unsplash.com/400x400/?sunglasses,accessories",
        category: "Accessories",
    },
    {
        id: 20,
        name: "Floor Lamp",
        price: 69.99,
        description: "Modern floor lamp with adjustable brightness.",
        image: "https://source.unsplash.com/400x400/?floor-lamp,lamp",
        category: "Home",
    },
    {
        id: 21,
        name: "Coffee Table",
        price: 149.99,
        description: "Wooden coffee table with storage shelf.",
        image: "https://source.unsplash.com/400x400/?coffee-table,furniture",
        category: "Furniture",
    },
    {
        id: 22,
        name: "Wireless Charger",
        price: 29.99,
        description: "Fast wireless charger compatible with most phones.",
        image: "https://source.unsplash.com/400x400/?wireless-charger,charger",
        category: "Electronics",
    },
    {
        id: 23,
        name: "Hiking Boots",
        price: 159.99,
        description: "Waterproof boots designed for hiking trails.",
        image: "https://source.unsplash.com/400x400/?hiking-boots,boots",
        category: "Footwear",
    },
    {
        id: 24,
        name: "Backpack",
        price: 69.99,
        description: "Durable backpack with multiple compartments.",
        image: "https://source.unsplash.com/400x400/?backpack,bag",
        category: "Accessories",
    },
    {
        id: 25,
        name: "Wall Clock",
        price: 29.99,
        description: "Silent wall clock with modern design.",
        image: "https://source.unsplash.com/400x400/?wall-clock,clock",
        category: "Home",
    },
    {
        id: 26,
        name: "Recliner Chair",
        price: 299.99,
        description: "Comfortable recliner with adjustable settings.",
        image: "https://source.unsplash.com/400x400/?recliner-chair,furniture",
        category: "Furniture",
    },
    {
        id: 27,
        name: "Portable Hard Drive",
        price: 89.99,
        description: "1TB external hard drive for backups.",
        image: "https://source.unsplash.com/400x400/?external-hard-drive,technology",
        category: "Electronics",
    },
    {
        id: 28,
        name: "Sandals",
        price: 29.99,
        description: "Casual sandals for summer wear.",
        image: "https://source.unsplash.com/400x400/?sandals,footwear",
        category: "Footwear",
    },
    {
        id: 29,
        name: "Beanie Hat",
        price: 14.99,
        description: "Warm knit beanie for cold weather.",
        image: "https://source.unsplash.com/400x400/?beanie,hat",
        category: "Accessories",
    },
    {
        id: 30,
        name: "Table Lamp",
        price: 45.99,
        description: "Compact lamp with touch controls and USB port.",
        image: "https://source.unsplash.com/400x400/?table-lamp,lamp",
        category: "Home",
    },
    {
        id: 31,
        name: "Bookshelf",
        price: 109.99,
        description: "Simple wooden bookshelf with 4 shelves.",
        image: "https://source.unsplash.com/400x400/?bookshelf,furniture",
        category: "Furniture",
    },
    {
        id: 32,
        name: "Noise-Cancelling Headphones",
        price: 129.99,
        description: "Over-ear headphones with active noise cancellation.",
        image: "https://source.unsplash.com/400x400/?noise-cancelling-headphones,headphones",
        category: "Electronics",
    },
];
